export const seedSilverIsraelProductImages: Record<string, readonly string[]> = {
  "elysia-alba-ring-silver-i-005": ["/brand/silver-israel/elysia-alba-ring-silver-i-005-01.avif"],
  "elysia-alba-ring-silver-ii-015": ["/brand/silver-israel/elysia-alba-ring-silver-ii-015-01.avif"],
  "elysia-alba-ring-silver-iii-025": ["/brand/silver-israel/elysia-alba-ring-silver-iii-025-01.avif"],
  "elysia-ariel-earrings-gold-069": ["/brand/silver-israel/elysia-ariel-earrings-gold-069-01.avif"],
  "elysia-ariel-earrings-silver-059": ["/brand/silver-israel/elysia-ariel-earrings-silver-059-01.avif"],
  "elysia-astra-bracelet-gold-082": ["/brand/silver-israel/elysia-astra-bracelet-gold-082-01.avif"],
  "elysia-astra-bracelet-silver-092": ["/brand/silver-israel/elysia-astra-bracelet-silver-092-01.avif"],
  "elysia-aurea-ring-gold-010": ["/brand/silver-israel/elysia-aurea-ring-gold-010-01.avif"],
  "elysia-aurea-ring-silver-i-020": ["/brand/silver-israel/elysia-aurea-ring-silver-i-020-01.avif"],
  "elysia-aurea-ring-silver-ii-030": ["/brand/silver-israel/elysia-aurea-ring-silver-ii-030-01.avif"],
  "elysia-aurora-necklace-gold-i-041": ["/brand/silver-israel/elysia-aurora-necklace-gold-i-041-01.avif"],
  "elysia-aurora-necklace-gold-ii-051": ["/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-01.avif", "/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-02.avif", "/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-03.avif", "/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-04.avif", "/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-05.avif", "/brand/silver-israel/elysia-aurora-necklace-gold-ii-051-06.avif"],
  "elysia-aurora-necklace-silver-031": ["/brand/silver-israel/elysia-aurora-necklace-silver-031-01.avif", "/brand/silver-israel/elysia-aurora-necklace-silver-031-02.avif"],
  "elysia-belle-ring-gold-i-019": ["/brand/silver-israel/elysia-belle-ring-gold-i-019-01.avif"],
  "elysia-belle-ring-gold-ii-029": ["/brand/silver-israel/elysia-belle-ring-gold-ii-029-01.avif"],
  "elysia-belle-ring-silver-009": ["/brand/silver-israel/elysia-belle-ring-silver-009-01.avif"],
  "elysia-bridal-set-095": ["/brand/silver-israel/elysia-bridal-set-095-01.avif"],
  "elysia-celeste-necklace-gold-i-032": ["/brand/silver-israel/elysia-celeste-necklace-gold-i-032-01.avif"],
  "elysia-celeste-necklace-gold-ii-042": ["/brand/silver-israel/elysia-celeste-necklace-gold-ii-042-01.avif"],
  "elysia-celeste-necklace-silver-052": ["/brand/silver-israel/elysia-celeste-necklace-silver-052-01.avif", "/brand/silver-israel/elysia-celeste-necklace-silver-052-02.avif", "/brand/silver-israel/elysia-celeste-necklace-silver-052-03.avif", "/brand/silver-israel/elysia-celeste-necklace-silver-052-04.avif", "/brand/silver-israel/elysia-celeste-necklace-silver-052-05.avif", "/brand/silver-israel/elysia-celeste-necklace-silver-052-06.avif"],
  "elysia-celine-earrings-gold-070": ["/brand/silver-israel/elysia-celine-earrings-gold-070-01.avif"],
  "elysia-celine-earrings-rose-gold-060": ["/brand/silver-israel/elysia-celine-earrings-rose-gold-060-01.avif"],
  "elysia-clara-ring-gold-i-008": ["/brand/silver-israel/elysia-clara-ring-gold-i-008-01.avif"],
  "elysia-clara-ring-gold-ii-018": ["/brand/silver-israel/elysia-clara-ring-gold-ii-018-01.avif"],
  "elysia-clara-ring-silver-028": ["/brand/silver-israel/elysia-clara-ring-silver-028-01.avif"],
  "elysia-classic-set-100": ["/brand/silver-israel/elysia-classic-set-100-01.avif"],
  "elysia-daphne-earrings-silver-i-061": ["/brand/silver-israel/elysia-daphne-earrings-silver-i-061-01.avif"],
  "elysia-daphne-earrings-silver-ii-071": ["/brand/silver-israel/elysia-daphne-earrings-silver-ii-071-01.avif"],
  "elysia-dew-earrings-silver-i-057": ["/brand/silver-israel/elysia-dew-earrings-silver-i-057-01.avif", "/brand/silver-israel/elysia-dew-earrings-silver-i-057-02.avif", "/brand/silver-israel/elysia-dew-earrings-silver-i-057-03.avif", "/brand/silver-israel/elysia-dew-earrings-silver-i-057-04.avif", "/brand/silver-israel/elysia-dew-earrings-silver-i-057-05.avif", "/brand/silver-israel/elysia-dew-earrings-silver-i-057-06.avif"],
  "elysia-dew-earrings-silver-ii-067": ["/brand/silver-israel/elysia-dew-earrings-silver-ii-067-01.avif"],
  "elysia-diana-necklace-gold-046": ["/brand/silver-israel/elysia-diana-necklace-gold-046-01.avif"],
  "elysia-diana-necklace-silver-036": ["/brand/silver-israel/elysia-diana-necklace-silver-036-01.avif"],
  "elysia-eden-bracelet-gold-i-084": ["/brand/silver-israel/elysia-eden-bracelet-gold-i-084-01.avif"],
  "elysia-eden-bracelet-gold-ii-094": ["/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-01.avif", "/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-02.avif", "/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-03.avif", "/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-04.avif", "/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-05.avif", "/brand/silver-israel/elysia-eden-bracelet-gold-ii-094-06.avif"],
  "elysia-elara-necklace-silver-i-035": ["/brand/silver-israel/elysia-elara-necklace-silver-i-035-01.avif"],
  "elysia-elara-necklace-silver-ii-045": ["/brand/silver-israel/elysia-elara-necklace-silver-ii-045-01.avif"],
  "elysia-gift-set-104": ["/brand/silver-israel/elysia-gift-set-104-01.avif"],
  "elysia-grace-bracelet-silver-i-079": ["/brand/silver-israel/elysia-grace-bracelet-silver-i-079-01.avif"],
  "elysia-grace-bracelet-silver-ii-089": ["/brand/silver-israel/elysia-grace-bracelet-silver-ii-089-01.avif"],
  "elysia-grace-ring-gold-i-001": ["/brand/silver-israel/elysia-grace-ring-gold-i-001-01.avif"],
  "elysia-grace-ring-gold-ii-011": ["/brand/silver-israel/elysia-grace-ring-gold-ii-011-01.avif"],
  "elysia-grace-ring-gold-iii-021": ["/brand/silver-israel/elysia-grace-ring-gold-iii-021-01.avif"],
  "elysia-grace-set-097": ["/brand/silver-israel/elysia-grace-set-097-01.avif"],
  "elysia-halo-earrings-gold-065": ["/brand/silver-israel/elysia-halo-earrings-gold-065-01.avif", "/brand/silver-israel/elysia-halo-earrings-gold-065-02.avif"],
  "elysia-halo-earrings-silver-055": ["/brand/silver-israel/elysia-halo-earrings-silver-055-01.avif"],
  "elysia-halo-ring-silver-i-003": ["/brand/silver-israel/elysia-halo-ring-silver-i-003-01.avif"],
  "elysia-halo-ring-silver-ii-013": ["/brand/silver-israel/elysia-halo-ring-silver-ii-013-01.avif"],
  "elysia-halo-ring-silver-iii-023": ["/brand/silver-israel/elysia-halo-ring-silver-iii-023-01.avif"],
  "elysia-halo-set-099": ["/brand/silver-israel/elysia-halo-set-099-01.avif"],
  "elysia-iris-necklace-silver-i-037": ["/brand/silver-israel/elysia-iris-necklace-silver-i-037-01.avif"],
  "elysia-iris-necklace-silver-ii-047": ["/brand/silver-israel/elysia-iris-necklace-silver-ii-047-01.avif"],
  "elysia-isla-ring-silver-i-007": ["/brand/silver-israel/elysia-isla-ring-silver-i-007-01.avif"],
  "elysia-isla-ring-silver-ii-017": ["/brand/silver-israel/elysia-isla-ring-silver-ii-017-01.avif"],
  "elysia-isla-ring-silver-iii-027": ["/brand/silver-israel/elysia-isla-ring-silver-iii-027-01.avif"],
  "elysia-ivy-bracelet-gold-081": ["/brand/silver-israel/elysia-ivy-bracelet-gold-081-01.avif"],
  "elysia-ivy-bracelet-silver-091": ["/brand/silver-israel/elysia-ivy-bracelet-silver-091-01.avif"],
  "elysia-line-bracelet-gold-077": ["/brand/silver-israel/elysia-line-bracelet-gold-077-01.avif"],
  "elysia-line-bracelet-silver-087": ["/brand/silver-israel/elysia-line-bracelet-silver-087-01.avif"],
  "elysia-lumi-earrings-gold-i-058": ["/brand/silver-israel/elysia-lumi-earrings-gold-i-058-01.avif", "/brand/silver-israel/elysia-lumi-earrings-gold-i-058-02.avif", "/brand/silver-israel/elysia-lumi-earrings-gold-i-058-03.avif", "/brand/silver-israel/elysia-lumi-earrings-gold-i-058-04.avif", "/brand/silver-israel/elysia-lumi-earrings-gold-i-058-05.avif", "/brand/silver-israel/elysia-lumi-earrings-gold-i-058-06.avif"],
  "elysia-lumi-earrings-gold-ii-068": ["/brand/silver-israel/elysia-lumi-earrings-gold-ii-068-01.avif"],
  "elysia-luna-bracelet-gold-i-078": ["/brand/silver-israel/elysia-luna-bracelet-gold-i-078-01.avif"],
  "elysia-luna-bracelet-gold-ii-088": ["/brand/silver-israel/elysia-luna-bracelet-gold-ii-088-01.avif"],
  "elysia-luna-ring-gold-i-012": ["/brand/silver-israel/elysia-luna-ring-gold-i-012-01.avif"],
  "elysia-luna-ring-gold-ii-022": ["/brand/silver-israel/elysia-luna-ring-gold-ii-022-01.avif"],
  "elysia-luna-ring-silver-002": ["/brand/silver-israel/elysia-luna-ring-silver-002-01.avif"],
  "elysia-luna-set-101": ["/brand/silver-israel/elysia-luna-set-101-01.avif"],
  "elysia-luxe-bracelet-gold-i-076": ["/brand/silver-israel/elysia-luxe-bracelet-gold-i-076-01.avif"],
  "elysia-luxe-bracelet-gold-ii-086": ["/brand/silver-israel/elysia-luxe-bracelet-gold-ii-086-01.avif"],
  "elysia-mila-bracelet-silver-i-083": ["/brand/silver-israel/elysia-mila-bracelet-silver-i-083-01.avif"],
  "elysia-mila-bracelet-silver-ii-093": ["/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-01.avif", "/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-02.avif", "/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-03.avif", "/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-04.avif", "/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-05.avif", "/brand/silver-israel/elysia-mila-bracelet-silver-ii-093-06.avif"],
  "elysia-mira-earrings-gold-062": ["/brand/silver-israel/elysia-mira-earrings-gold-062-01.avif"],
  "elysia-mira-earrings-silver-072": ["/brand/silver-israel/elysia-mira-earrings-silver-072-01.avif", "/brand/silver-israel/elysia-mira-earrings-silver-072-02.avif", "/brand/silver-israel/elysia-mira-earrings-silver-072-03.avif", "/brand/silver-israel/elysia-mira-earrings-silver-072-04.avif", "/brand/silver-israel/elysia-mira-earrings-silver-072-05.avif", "/brand/silver-israel/elysia-mira-earrings-silver-072-06.avif"],
  "elysia-muse-necklace-gold-044": ["/brand/silver-israel/elysia-muse-necklace-gold-044-01.avif"],
  "elysia-muse-necklace-silver-i-034": ["/brand/silver-israel/elysia-muse-necklace-silver-i-034-01.avif"],
  "elysia-muse-necklace-silver-ii-054": ["/brand/silver-israel/elysia-muse-necklace-silver-ii-054-01.avif", "/brand/silver-israel/elysia-muse-necklace-silver-ii-054-02.avif", "/brand/silver-israel/elysia-muse-necklace-silver-ii-054-03.avif", "/brand/silver-israel/elysia-muse-necklace-silver-ii-054-04.avif", "/brand/silver-israel/elysia-muse-necklace-silver-ii-054-05.avif", "/brand/silver-israel/elysia-muse-necklace-silver-ii-054-06.avif"],
  "elysia-muse-set-102": ["/brand/silver-israel/elysia-muse-set-102-01.avif"],
  "elysia-noelle-necklace-gold-048": ["/brand/silver-israel/elysia-noelle-necklace-gold-048-01.avif"],
  "elysia-noelle-necklace-silver-038": ["/brand/silver-israel/elysia-noelle-necklace-silver-038-01.avif"],
  "elysia-nora-bracelet-gold-i-080": ["/brand/silver-israel/elysia-nora-bracelet-gold-i-080-01.avif"],
  "elysia-nora-bracelet-gold-ii-090": ["/brand/silver-israel/elysia-nora-bracelet-gold-ii-090-01.avif"],
  "elysia-nora-ring-gold-i-006": ["/brand/silver-israel/elysia-nora-ring-gold-i-006-01.avif"],
  "elysia-nora-ring-gold-ii-016": ["/brand/silver-israel/elysia-nora-ring-gold-ii-016-01.avif"],
  "elysia-nora-ring-silver-026": ["/brand/silver-israel/elysia-nora-ring-silver-026-01.avif"],
  "elysia-opal-earrings-gold-073": ["/brand/silver-israel/elysia-opal-earrings-gold-073-01.avif", "/brand/silver-israel/elysia-opal-earrings-gold-073-02.avif", "/brand/silver-israel/elysia-opal-earrings-gold-073-03.avif", "/brand/silver-israel/elysia-opal-earrings-gold-073-04.avif", "/brand/silver-israel/elysia-opal-earrings-gold-073-05.avif", "/brand/silver-israel/elysia-opal-earrings-gold-073-06.avif"],
  "elysia-opal-earrings-silver-063": ["/brand/silver-israel/elysia-opal-earrings-silver-063-01.avif", "/brand/silver-israel/elysia-opal-earrings-silver-063-02.avif"],
  "elysia-pearl-earrings-gold-066": ["/brand/silver-israel/elysia-pearl-earrings-gold-066-01.avif"],
  "elysia-pearl-earrings-silver-056": ["/brand/silver-israel/elysia-pearl-earrings-silver-056-01.avif"],
  "elysia-pearl-necklace-gold-i-033": ["/brand/silver-israel/elysia-pearl-necklace-gold-i-033-01.avif"],
  "elysia-pearl-necklace-gold-ii-043": ["/brand/silver-israel/elysia-pearl-necklace-gold-ii-043-01.avif"],
  "elysia-pearl-necklace-silver-053": ["/brand/silver-israel/elysia-pearl-necklace-silver-053-01.avif", "/brand/silver-israel/elysia-pearl-necklace-silver-053-02.avif", "/brand/silver-israel/elysia-pearl-necklace-silver-053-03.avif", "/brand/silver-israel/elysia-pearl-necklace-silver-053-04.avif", "/brand/silver-israel/elysia-pearl-necklace-silver-053-05.avif", "/brand/silver-israel/elysia-pearl-necklace-silver-053-06.avif"],
  "elysia-pearl-set-098": ["/brand/silver-israel/elysia-pearl-set-098-01.avif"],
  "elysia-rhea-earrings-gold-064": ["/brand/silver-israel/elysia-rhea-earrings-gold-064-01.avif"],
  "elysia-rhea-earrings-silver-074": ["/brand/silver-israel/elysia-rhea-earrings-silver-074-01.avif", "/brand/silver-israel/elysia-rhea-earrings-silver-074-02.avif", "/brand/silver-israel/elysia-rhea-earrings-silver-074-03.avif", "/brand/silver-israel/elysia-rhea-earrings-silver-074-04.avif", "/brand/silver-israel/elysia-rhea-earrings-silver-074-05.avif", "/brand/silver-israel/elysia-rhea-earrings-silver-074-06.avif"],
  "elysia-serene-ring-gold-i-004": ["/brand/silver-israel/elysia-serene-ring-gold-i-004-01.avif"],
  "elysia-serene-ring-gold-ii-014": ["/brand/silver-israel/elysia-serene-ring-gold-ii-014-01.avif"],
  "elysia-serene-ring-gold-iii-024": ["/brand/silver-israel/elysia-serene-ring-gold-iii-024-01.avif"],
  "elysia-signature-set-096": ["/brand/silver-israel/elysia-signature-set-096-01.avif"],
  "elysia-soleil-necklace-silver-i-039": ["/brand/silver-israel/elysia-soleil-necklace-silver-i-039-01.avif"],
  "elysia-soleil-necklace-silver-ii-049": ["/brand/silver-israel/elysia-soleil-necklace-silver-ii-049-01.avif"],
  "elysia-tennis-bracelet-silver-i-075": ["/brand/silver-israel/elysia-tennis-bracelet-silver-i-075-01.avif"],
  "elysia-tennis-bracelet-silver-ii-085": ["/brand/silver-israel/elysia-tennis-bracelet-silver-ii-085-01.avif"],
  "elysia-timeless-set-103": ["/brand/silver-israel/elysia-timeless-set-103-01.avif"],
  "elysia-vera-necklace-gold-040": ["/brand/silver-israel/elysia-vera-necklace-gold-040-01.avif"],
  "elysia-vera-necklace-silver-050": ["/brand/silver-israel/elysia-vera-necklace-silver-050-01.avif", "/brand/silver-israel/elysia-vera-necklace-silver-050-02.avif", "/brand/silver-israel/elysia-vera-necklace-silver-050-03.avif", "/brand/silver-israel/elysia-vera-necklace-silver-050-04.avif", "/brand/silver-israel/elysia-vera-necklace-silver-050-05.avif", "/brand/silver-israel/elysia-vera-necklace-silver-050-06.avif"],
};
