export const giftTerms = [
  "gift",
  "present",
  "occasion",
  "birthday",
  "anniversary",
  "holiday",
  "wedding gift",
  "מתנה",
  "מתנות",
  "למתנה",
  "יום הולדת",
  "אירוע",
  "יום נישואין",
] as const;

export const giftRecipientTerms = [
  "mom",
  "mother",
  "wife",
  "partner",
  "girlfriend",
  "friend",
  "bride",
  "אמא",
  "אמא שלי",
  "בת זוג",
  "אשתי",
  "חברה",
  "חברה שלי",
  "כלה",
  "אחות",
  "סבתא",
] as const;

export const giftOccasionTerms = [
  "birthday",
  "anniversary",
  "wedding",
  "holiday",
  "יום הולדת",
  "יום נישואין",
  "חתונה",
  "אירוע",
  "חג",
  "לידה",
] as const;

export const catalogTerms = [
  "ring",
  "rings",
  "necklace",
  "necklaces",
  "chain",
  "bracelet",
  "bracelets",
  "earring",
  "earrings",
  "jewelry",
  "jewellery",
  "jewel",
  "budget",
  "price",
  "gold",
  "white gold",
  "yellow gold",
  "diamond",
  "diamonds",
  "silver",
  "pearl",
  "engagement",
  "proposal",
  "wedding",
  "bridal",
  "bride",
  "טבעת",
  "טבעות",
  "שרשרת",
  "שרשראות",
  "תליון",
  "צמיד",
  "צמידים",
  "עגיל",
  "עגילים",
  "תכשיט",
  "תכשיטים",
  "תקציב",
  "מחיר",
  "שח",
  "₪",
  "זהב",
  "זהב לבן",
  "זהב צהוב",
  "יהלום",
  "יהלומים",
  "כסף",
  "פנינה",
  "פנינים",
  "כלה",
  "חתונה",
  "אירוסין",
  "הצעת נישואין",
  "יום יום",
] as const;

export const styleDescriptorTerms = [
  "delicate",
  "soft",
  "subtle",
  "classic",
  "minimalist",
  "modern",
  "everyday",
  "elegant",
  "עדין",
  "עדינה",
  "עדינים",
  "עדינות",
  "קלאסי",
  "קלאסית",
  "מינימליסטי",
  "מינימליסטית",
  "מודרני",
  "מודרנית",
  "יומיומי",
  "יומיומית",
  "אלגנטי",
  "אלגנטית",
  "פחות כבד",
  "לא כבד",
] as const;

export const catalogFollowUpTerms = [
  "similar",
  "another",
  "different",
  "more",
  "less",
  "instead",
  "option",
  "אפשר",
  "עוד",
  "דומה",
  "אחר",
  "אחרת",
  "אופציה",
  "חלופה",
  "יותר",
  "פחות",
  "במקום",
] as const;

export const styleProfileTerms = [
  "style profile",
  "save my style",
  "save style",
  "remember my style",
  "save these preferences",
  "profile",
  "ring size",
  "פרופיל סגנון",
  "פרופיל סטייל",
  "שמור סגנון",
  "שמור לי סגנון",
  "שמרי לי סגנון",
  "תשמרי לי סגנון",
  "שמרי לי פרופיל",
  "זכרי את הסגנון",
  "שמרי העדפות",
  "מידת טבעת",
  "סגנון אישי",
] as const;

export const tryOnTerms = [
  "try on",
  "try it on",
  "virtual try",
  "virtual try on",
  "virtual fitting",
  "webar",
  "measure",
  "מדידה",
  "למדוד",
  "לנסות",
  "נסה עלי",
  "נסה עליי",
  "נסי עליי",
  "אראה עלי",
  "אראה עליי",
  "וירטואלית",
] as const;

export const orderSupportPhrases = [
  "order status",
  "track order",
  "track my order",
  "tracking order",
  "where is my order",
  "when will my order",
  "status of my order",
  "support for my order",
  "delivery status",
  "shipment status",
  "סטטוס הזמנה",
  "סטטוס ההזמנה",
  "מעקב הזמנה",
  "מעקב משלוח",
  "איפה ההזמנה",
  "איפה המשלוח",
  "ההזמנה שלי",
  "המשלוח שלי",
  "מתי ההזמנה",
  "מתי המשלוח",
] as const;

export const orderSupportActionTerms = [
  "status",
  "track",
  "tracking",
  "support",
  "arrive",
  "arrival",
  "refund",
  "return",
  "cancel",
  "סטטוס",
  "מעקב",
  "איפה",
  "מתי",
  "הגיע",
  "מגיעה",
  "תמיכה",
  "שירות",
  "ביטול",
  "לבטל",
  "החזרה",
  "זיכוי",
] as const;

export const orderIdentityTerms = [
  "order",
  "my order",
  "purchase",
  "shipment",
  "delivery",
  "הזמנה",
  "ההזמנה",
  "הזמנתי",
  "משלוח",
  "המשלוח",
] as const;

export const orderReferenceTerms = [
  "order number",
  "order #",
  "מספר הזמנה",
  "מס הזמנה",
] as const;

export const promptInjectionTerms = [
  "ignore previous",
  "ignore the previous",
  "ignore all previous",
  "disregard previous",
  "system prompt",
  "reveal prompt",
  "show system",
  "developer message",
  "התעלם מההוראות",
  "התעלמי מההוראות",
  "תתעלמי מההוראות",
  "פרומפט מערכת",
  "הוראות מערכת",
  "חשפי את ההנחיות",
  "גלי את ההנחיות",
] as const;
